### ISSUE TITLE
Apple Mach-O Linker Error "_OBJC_CLASS_$_Crashlytics", referenced from

### ISSUE THREAD

**Issue by luna-moonfang** [bpoplauschi/CrashlyticsFramework#12]
Hi, I am using CocoaPods to add CrashlyticsFramework.
First, add run script `./Crashlytics.framework/run xxxxxx` in Xcode. Compile and success. Check.
Add `pod 'CrashlyticsFramework', '~> 2.2.2'` in Podfile. Compile and success. Check.
Import `<Crashlytics/Crashlytics.h>`. Compile and success. Check.
Add code `[Crashlytics startWithAPIKey:@"xxxxxx"];`. Compile and Failed. Got these message:

> Undefined symbols for architecture i386:
>   "_OBJC_CLASS_$_Crashlytics", referenced from:
>       objc-class-ref in AppDelegate.o
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I check the `Pods.xcconfig`, where the search paths were in, and make sure they are all there. Adde it as the based-on config file. Add `$(inherited)` to target's search path.

**So what did I miss?** Could anyone help?
## Solved:

By adding every item in `Pods.xcconfig` to Xcode target's settings. I only added search paths. In fact, `other linker flag` also needs the `$(inherited)`. And that solve the problem.

**Comment by yong076** [comment]
You Save my time. Thanks.
