### ISSUE TITLE
License not suitable for automatically displaying in apps?

### ISSUE THREAD

**Issue by rsanchezsaez** [bpoplauschi/CrashlyticsFramework#17]
Some apps which use Cocoapods automatically build a Settings bundle which displays all the LICENSE files from the pods in use, in an aggregated "Acknowledgements" section on the iOS Settings app. See our app, [Seene](www.appstore.com/seene), for an example of this.

Normally most of them are MIT, etc., quite short licenses. Since last updating the Crashlytics cocoapod, it became *huge*, as it seems to include the whole Terms & Conditions.

Are you sure you want this to be the license file on the repo? (which will be potentially facing the 3rd party users of apps which use Crashlytics through the cocoapod, such as Seene). One could argue that the Terms & Conditions is an agreement between Crashlytics and the maker of the app, and that there is no need to show it from a Crashlytics-enabled app to a third party user.

**Comment by Pipen** [comment]
I agree with @rsanchezsaez the LICENSE should be used as LICENSE, not as a terms and condition.

**Comment by bpoplauschi** [comment]
@rsanchezsaez or @Pipen could one of you make a pull request with this?

**Comment by Pipen** [comment]
I would say that what should be included is probably http://try.crashlytics.com/terms/opensource.txt what ya think?

**Comment by bpoplauschi** [comment]
This is the list of open source projects used by Crashlytics. We should include the license for using the Crashlytics framework. Damn, those legal issues are not easy to grasp

**Comment by Pipen** [comment]
The way I see it. When crashlytics include their lib the way they want by letting the desktop tool inject the library they don't add anything about the LICENSE which implies that they aren't that bother by it. But its important that we as end user make sure that the libs they are using actually are mentioned in a propert way

**Comment by bpoplauschi** [comment]
No longer applicable, as this repo is deprecated in favour of the official Fabric Cocoapods distribution.
