### ISSUE TITLE
Linker warning in Xcode 6

### ISSUE THREAD

**Issue by lyahdav** [bpoplauschi/CrashlyticsFramework#18]
We started getting this build warning after upgrading to Xcode 6:

```
Warning: Auto-Linking supplied 'Pods/CrashlyticsFramework/Crashlytics.framework/Crashlytics', framework linker option at Pods/CrashlyticsFramework/Crashlytics.framework/Crashlytics is not a dylib
```

Everything seems to work fine with Crashlytics, but it would be nice to not have that warning when we build. Any ideas?

**Comment by lyahdav** [comment]
We had this issue again when upgrading to Crashlytics using Fabric, except the error came from Fabric:
`ld: warning: Auto-Linking supplied 'Pods/Fabric/Fabric.framework/Fabric', framework linker option at Pods/Fabric/Fabric.framework/Fabric is not a dylib`.
The fix was to add the Fabric and Crashlytics pods to our tests target:
```
pod 'Fabric'
pod 'Crashlytics'

target :Specs, :exclusive => true do
    pod 'Kiwi', '~> 2.4'
    pod 'Fabric'
    pod 'Crashlytics'
end
```
Seems a little weird to include the pods twice, but it fixes the warning.

**Comment by bpoplauschi** [comment]
Hmmm, weird

**Comment by trant** [comment]
Got the same problem here
