### ISSUE TITLE
Automatically add required Run Script section

### ISSUE THREAD

**Issue by brennanMKE** [bpoplauschi/CrashlyticsFramework#20]
http://stackoverflow.com/questions/20072937/add-run-script-build-phase-to-xcode-project-from-podspec

I am not a Ruby developer so it would take me a while to piece it together but with a little help it might be possible to include the required Run Script section for each of the build targets. (I typically have at least 2 or 3 build targets to support a Staging and Production target and sometimes a Mock target.)

What the Podspec could not include is the keys used by the `run` script. I do not know how a Podspec would specify a Run Script and take in local parameters for this purpose or if that is even supported with CocoaPods at the moment.

I'd like to help make this work if you'd like to collaborate on it.

**Comment by lemonkey-medhelp** [comment]
Unfortunately prepare_command isn't used when the internal pod is referenced using path (local dev pod).

**Comment by bpoplauschi** [comment]
No longer applicable, as this repo is deprecated in favour of the official Fabric Cocoapods distribution.
