### ISSUE TITLE
Unable to find a specification for `CrashlyticsFramework (~> 2.2)`

### ISSUE THREAD

**Issue by powerje** [bpoplauschi/CrashlyticsFramework#25]
In my Podfile I have:
`pod 'CrashlyticsFramework', '~> 2.2'`

and doing a`pod install` I receive the error:
Unable to find a specification for `CrashlyticsFramework (~> 2.2)`

Using the spec directly works:
`pod 'CrashlyticsFramework', :podspec => 'https://raw.githubusercontent.com/bpoplauschi/CrashlyticsFramework/master/CrashlyticsFramework.podspec'`

Looks like a CocoaPods bug but I figured I'll report it here in case anyone else runs into this. I am using CocoaPods 0.35.0.

**Comment by powerje** [comment]
Appears to have been a problem with my CocoaPods install. Basically all pods that I didn't specify by podspec were not working. Blowing up CocoaPods and re-installing it / running 'pod setup' fixed my issue.

**Comment by bpoplauschi** [comment]
:+1:
