### ISSUE TITLE
Auto linking warning when mixing Swift/Obj C in Xcode 6.

### ISSUE THREAD

**Issue by admmasters** [bpoplauschi/CrashlyticsFramework#26]
Auto-Linking supplied '/$ProjectPath/Crashlytics.framework/Crashlytics', framework linker option at /$ProjectPath/Qinec/Emma-iPad/Crashlytics.framework/Crashlytics is not a dylib - this warning occurs on Xcode 6 when you choose to use mixed mode Swift/Obj C code. Doesn't throw this warning until you try and add some Swift to an existing Obj C code base.

**Comment by bpoplauschi** [comment]
No longer applicable, as this repo is deprecated in favour of the official Fabric Cocoapods distribution.
