### ISSUE TITLE
Upgrade to 3.0 SDK ?

### ISSUE THREAD

**Issue by ghugues** [bpoplauschi/CrashlyticsFramework#29]
Hi !
Seems Crashlytics released a new version of their SDK today. Could you make the update ?
Thanks,
Guillaume

**Comment by sodastsai** [comment]
It seems Crashlytics 3.0 must be worked with Twitter's Fabric.

**Comment by fnxpt** [comment]
Submitted a pull request to include updated frameworks

**Comment by tbaranes** [comment]
Any news about updating this repot?

**Comment by fnxpt** [comment]
In order to use the new version you have to use fabric, so just use fabric
repo

On Tuesday, May 26, 2015, Tom Baranes <notifications@github.com> wrote:

> Any news about updating this repot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bpoplauschi/CrashlyticsFramework/issues/29#issuecomment-105420347>
> .
>


-- 
Sent from a mobile device

**Comment by tbaranes** [comment]
Yes, I know that. The interesting part of this repot that is a pod, that's why I'm asking about it. So, this repot won't be updated?

**Comment by bpoplauschi** [comment]
It seems the new Crashlytics framework format is not compatible with the old one. I've failed to isolate just that framework out of Fabric. It looks like for now, the way to go is https://github.com/zergtmn/Fabric, as now Crashlytics depends on the Fabric framework and things are more complicated than they used to
