### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dorongutman** [bpoplauschi/CrashlyticsFramework#3]
After adding the appropriate line to the Podfile and running `pod update` I'm getting the following error when I build the project:

```
ld: framework not found Crashlytics
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

At first I thought it might be related to the build phase script I've added, but even after I removed it completely I'm still getting that error.

Xcode 5

**Comment by FedeCugliandolo** [comment]
I stil have the same issue:
./Pods/CrashlyticsFramework/Crashlytics.framework/run: No such file or directory

any help?

**Comment by bpoplauschi** [comment]
@FedeCugliandolo you need to identify the proper path for the run script (where it is installed in your project).

**Comment by FedeCugliandolo** [comment]
@bpoplauschi thanks for your answer. I solved it adding two dots at the beginning: ../Pods/Crashlytics....

**Comment by bpoplauschi** [comment]
:+1:

**Comment by RacZo** [comment]
Had the same issue and all I had to do was to go to the Project target, Build Phases, Tun Script and change it to ./Pods/CrashlyticsFramework/Crashlytics.framework/run

That did the trick.
