### ISSUE TITLE
Deprecate in favor of the new official pod

### ISSUE THREAD

**Issue by AliSoftware** [bpoplauschi/CrashlyticsFramework#31]
Fabric recently released Crashlytics, TwitterKit, Digits and Fabric as official pods on CocoaPods Trunk: https://cocoapods.org/owners/7558

This means that that seems now like their official distribution channel, or at least that they will maintain those pods regularly, so them being the official account, you should probably [deprecate your pod in favor of theirs](https://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of)?

**Comment by phatblat** [comment]
:+1: Thanks for the heads up!

**Comment by bpoplauschi** [comment]
I'm deprecating it as we speak. Just need to make a PR on Specs.

**Comment by AliSoftware** [comment]
Note that those Fabrics pod are quite early (they have just pushed them on trunk) and not sure if they work out of the box. Maybe you could wait a bit until it's officially stated in their documentation or sthg.

**Comment by bpoplauschi** [comment]
They have already beta-tested those so I expect no issues. Plus the deprecation is just a warning, won't prevent people from using this pod.
